# Generated by Django 4.2 on 2023-04-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_attendancemodel_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(blank=True, max_length=30)),
                ('embedding', models.BinaryField()),
            ],
        ),
    ]
